spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/user
    username: postgres
    password: postgres

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
