prometheus:
  kube-state-metrics:
    enabled: true
  prometheus-node-exporter:
    enabled: true
  prometheus-pushgateway:
    enabled: true
  server:
    extraFlags:
      - "enable-feature=otlp-write-receiver"
      - "enable-feature=remote-write-receiver"
      # otlp-write-receiver
      # remote-write-receiver
  # storage:
  #   tsdb:
  #     out_of_order_time_window: 10m
