prometheus:
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  server:
    # image:
    #   repository: prom/prometheus
    #   tag: v2.52.0
    extraFlags:
      - "web.enable-remote-write-receiver"
      - "enable-feature=otlp-write-receiver"
