apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: LoadBalancer
  selector:
    app: my-user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: LoadBalancer
  selector:
    app: my-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: dashboard
    - protocol: TCP
      port: 4317
      targetPort: 4317
      name: grpc
    - protocol: TCP
      port: 4318
      targetPort: 4318
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  selector:
    app: my-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432