FROM grafana/otel-lgtm:0.6.0
COPY ./dashboard-template /otel-lgtm/dashboard-template
COPY ./dashboards /otel-lgtm/grafana-v11.0.0/conf/provisioning/dashboards
COPY ./datasources /otel-lgtm/grafana-v11.0.0/conf/provisioning/datasources