opentelemetry-collector:
  mode: deployment
  image:
    repository: "otel/opentelemetry-collector-contrib"
    tag: "0.102.1"
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint:
          http: 
            endpoint:
    processors:
      batch: {}
    exporters:
      otlphttp/logs:
        endpoint: http://loki:3100/otlp
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/logs]
      
          
          