apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://localhost:9090
    jsonData:
      timeInterval: 60s
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo
          urlDisplayLabel: 'Trace: $${__value.raw}'

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://localhost:3200
    jsonData:
      # tracesToLogs:
      #   datasourceUid: 'loki'
      #   mappedTags: [{ key: 'service.name', value: 'service_name' }]
      #   mapTagNamesEnabled: true
      #   filterByTraceID: true
      tracesToLogsV2:
        datasourceUid: 'loki'
        tags: [{ key: 'service.name', value: 'service_name' }]
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{$${__tags}} | trace_id="$${__span.traceId}"'
      serviceMap:
        datasourceUid: 'prometheus'
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'

  - name: Loki
    type: loki
    uid: loki
    url: http://localhost:3100
    jsonData:
      derivedFields:
        - name: 'trace_id'
          matcherRegex: '"traceid":"(\w+)"'
          url: '$${__value.raw}'
          datasourceUid: 'tempo'